version: '3.8'

networks:
  service:

services:
  db:
    image: postgres:16
    restart: always
    container_name: survival-database
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: